"""Added paypal default info renamed.

Revision ID: 8b4f9f4b4085
Revises: b0a5628fef94
Create Date: 2022-01-25 10:25:34.971597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4f9f4b4085'
down_revision = 'b0a5628fef94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paypal_details', sa.String(length=120), nullable=True))
    op.drop_column('user', 'paypal_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paypal_email', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('user', 'paypal_details')
    # ### end Alembic commands ###
