"""Added timezones

Revision ID: a514369167f8
Revises: e7f088c3f0e9
Create Date: 2021-10-02 17:43:18.952673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a514369167f8'
down_revision = 'e7f088c3f0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_zone', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_zone')
    # ### end Alembic commands ###
