"""Added Paypal email info

Revision ID: e4a047d0d355
Revises: b0a5628fef94
Create Date: 2022-01-25 10:01:47.558381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a047d0d355'
down_revision = 'b0a5628fef94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paypal_email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['paypal_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'paypal_email')
    # ### end Alembic commands ###
