"""Added Credits to User.

Revision ID: 00300647cd9a
Revises: 608f30e10b13
Create Date: 2021-10-14 11:37:54.135588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00300647cd9a'
down_revision = '608f30e10b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credits')
    # ### end Alembic commands ###
