"""Added timezones

Revision ID: 608f30e10b13
Revises: e7f088c3f0e9
Create Date: 2021-10-02 17:51:10.348153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608f30e10b13'
down_revision = 'e7f088c3f0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_zone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_zone')
    # ### end Alembic commands ###
