"""Added paypal stuff

Revision ID: 7ce7040b6afa
Revises: b0a5628fef94
Create Date: 2022-01-25 10:29:00.242547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce7040b6afa'
down_revision = 'b0a5628fef94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paypal_info', sa.String(length=120), nullable=True))
    #op.drop_column('user', 'paypal_details')
    #op.drop_column('user', 'paypal_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('user', sa.Column('paypal_email', sa.VARCHAR(length=120), nullable=True))
    #op.add_column('user', sa.Column('paypal_details', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('user', 'paypal_info')
    # ### end Alembic commands ###
