"""Created Tutor Application Database

Revision ID: b0a5628fef94
Revises: 00300647cd9a
Create Date: 2022-01-19 12:01:06.406341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a5628fef94'
down_revision = '00300647cd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('verbal_score', sa.Integer(), nullable=False),
    sa.Column('quant_score', sa.Integer(), nullable=False),
    sa.Column('awa_score', sa.Float(), nullable=False),
    sa.Column('video_link', sa.String(length=250), nullable=False),
    sa.Column('time_zone', sa.String(length=40), nullable=True),
    sa.Column('misc_info', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_application')
    # ### end Alembic commands ###
