"""added skype and hangout id to db

Revision ID: e7f088c3f0e9
Revises: f83c212dbb11
Create Date: 2021-08-28 15:14:32.198083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f088c3f0e9'
down_revision = 'f83c212dbb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skype_id', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('hangouts_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hangouts_id')
    op.drop_column('user', 'skype_id')
    # ### end Alembic commands ###
