"""Added Reviews DB with a FIXED score

Revision ID: f83c212dbb11
Revises: e4db3c58ea87
Create Date: 2021-07-18 17:04:16.869827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83c212dbb11'
down_revision = 'e4db3c58ea87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'review_score')
    # ### end Alembic commands ###
